Repository iterative/dvc.org, pull requests merged in 2020-03, with the labels that each got.

#1029 cmd ref: command options impros and consistency
  public/static/docs/command-reference/add.md
  public/static/docs/command-reference/fetch.md
  public/static/docs/command-reference/gc.md
  public/static/docs/command-reference/get.md
  public/static/docs/command-reference/import-url.md
  public/static/docs/command-reference/import.md
  public/static/docs/command-reference/pull.md
  public/static/docs/command-reference/push.md
  public/static/docs/command-reference/repro.md
  public/static/docs/command-reference/run.md
  public/static/docs/command-reference/status.md
  public/static/docs/sidebar.json
Labels: doc-content, enhancement

#1067 tests: links: misc fixes
  scripts/exclude-links.txt
  scripts/link-check-git-all.sh
  scripts/link-check-git-diff.sh
  scripts/link-check.sh
Labels: bug, doc-engine, priority-p1

#1023 cmd-ref: document new gc behavior
  content/docs/command-reference/gc.md
Labels: doc-content

#1076 tests: links: add missing & sort
  scripts/exclude-links.txt
  scripts/link-check-git-all.sh
  scripts/link-check-git-diff.sh
  scripts/link-check.sh
Labels: bug, priority-p1

#1077 tests: links: exit 0 on empty diffs
  scripts/link-check-git-diff.sh
Labels: bug, priority-p1

#1082 [HOTFIX] get-started: restore index in nav (bad recent merge)
  content/docs/sidebar.json
  content/docs/tutorials/get-started/index.md
Labels: bug
