Repository iterative/dvc.org, pull requests merged in 2020-04, with the labels that each got.

#1090 cmd-ref: make changes related to update --rev
  content/docs/command-reference/import.md
  content/docs/command-reference/update.md
Labels: doc-content

#1054 cmd-ref: document checkout displaying changes
  content/docs/command-reference/checkout.md
  content/docs/use-cases/shared-development-server.md
  content/docs/use-cases/versioning-data-and-model-files.md
Labels: doc-content

#1169 test: link-check: misc fixes
  scripts/exclude-links.txt
  scripts/link-check-git-all.sh
  scripts/link-check-git-diff.sh
  scripts/link-check.sh
Labels: bug, enhancement, research

#1189 test: link-check: trim and manage exclusions
  .circleci/config.yml
  package.json
  scripts/exclude-links-check.sh
  scripts/exclude-links.txt
  scripts/link-check-git-all.sh
  scripts/link-check-git-diff.sh
  scripts/link-check.sh
  scripts/utils.sh
Labels: enhancement, website

#1190 link-check: fix exclusions
  scripts/exclude-links-check.sh
  scripts/exclude-links.txt
  scripts/link-check-git-all.sh
Labels: bug, website

#1193 link-check: fix CI daily
  scripts/link-check-git-all.sh
Labels: bug, website

#1194 test: abstract all helpers to utils.sh
  scripts/exclude-links-check.sh
  scripts/link-check-git-all.sh
  scripts/link-check-git-diff.sh
  scripts/link-check.sh
  scripts/utils.sh
Labels: enhancement
