Repository iterative/dvc.org, pull requests merged in 2020-12, with the labels that each got.

#1974 plots: update confusion matrix examples
  static/img/plots_diff_confusion.svg
  static/img/plots_show_confusion.svg
Labels: doc-content

#2002 Update diff.md
  content/docs/command-reference/diff.md
Labels: ⏳ awaiting-dvc-merge

#1983 docs: doc repro --glob and update targets arg info.
  content/docs/command-reference/repro.md
Labels: doc-content

#2031 params: document --targets option
  content/docs/command-reference/params/diff.md
Labels: ⏳ awaiting-dvc-merge

#2039 [2.0] dvc.yaml: doc isexec field
  content/docs/user-guide/dvc-files-and-directories.md
Labels: 2.0 release
