Repository iterative/dvc.org, pull requests merged in 2021-02, with the labels that each got.

#2140 config: add docs for s3.configpath
  content/docs/command-reference/remote/modify.md
Labels: ⏳ awaiting-dvc-merge

#2000 cmd: doc pull --glob
  content/docs/command-reference/pull.md
Labels: ⏳ awaiting-dvc-merge

#2028 cli: config: add docs for --show-origin
  content/docs/command-reference/config.md
Labels: ⏳ awaiting-dvc-merge

#2122 get, get-url: add --jobs option
  content/docs/command-reference/get-url.md
  content/docs/command-reference/get.md
  content/docs/command-reference/import-url.md
  content/docs/command-reference/import.md
Labels: 2.0 release

#2163 cml: doc titles [SEO] and other fixes
  content/docs/cml/cml-with-npm.md
  content/docs/cml/index.md
  content/docs/cml/self-hosted-runners.md
  content/docs/cml/start-github.md
  content/docs/sidebar.json
  content/docs/user-guide/contributing/docs.md
Labels: bug

#2146 guide: Experiment Management
  content/docs/index.md
  content/docs/sidebar.json
  content/docs/start/experiments.md
  content/docs/user-guide/basic-concepts/experiment.md
  content/docs/user-guide/basic-concepts/run-cache.md
  content/docs/user-guide/experiment-management.md
  content/docs/user-guide/project-structure/internal-files.md
  content/docs/user-guide/project-structure/pipelines-files.md
  content/docs/user-guide/related-technologies.md
  content/docs/user-guide/what-is-dvc.md
Labels: 2.0 release
