Repository iterative/dvc.org, pull requests merged in 2021-09, with the labels that each got.

#2781 ref: correct dvctable highlighter
  content/docs/command-reference/exp/remove.md
  content/docs/user-guide/experiment-management/cleaning-experiments.md
Labels: bug

#2404 docs: use cases: add CI/CD for ML
  content/docs/command-reference/get.md
  content/docs/command-reference/plots/show.md
  content/docs/sidebar.json
  content/docs/start/data-pipelines.md
  content/docs/studio/user-guide/prepare-repositories.md
  content/docs/studio/user-guide/run-experiments.md
  content/docs/use-cases/ci-cd-for-machine-learning.md
  content/docs/use-cases/data-registries.md
  content/docs/use-cases/versioning-data-and-model-files/index.md
  static/img/cicd4ml-0.png
  static/img/cicd4ml-1.png
Labels: doc-content

#2779 yarn upgrade && yarn format-all
  content/docs/user-guide/contributing/blog.md
  package.json
  scripts/deploy-with-s3.js
  src/components/Blog/Feed/Item/index.tsx
  src/components/Blog/Post/HeroPic/index.tsx
  src/components/Community/Learn/index.tsx
  src/components/Community/Meet/index.tsx
  src/components/Documentation/Markdown/index.tsx
  src/components/DownloadButton/index.tsx
  src/components/Paginator/LocationContext/index.ts
  src/gatsby/models/authors/parse-link.js
  src/templates/blog-home.tsx
  src/templates/blog-post.tsx
  src/templates/blog-tags.tsx
  yarn.lock
Labels: dependencies, 🏠 housekeeping

#2810 replace sourcerer -> contrib.rocks
  README.md
Labels: p2-nice-to-have, 🏠 housekeeping

#2762 Added -n/--num option
  content/docs/command-reference/exp/show.md
Labels: dvc-update

#2774 config: sync local/CI Prettier and Restyled
  .prettierrc
  .restyled.yaml
Labels: dependencies

#2731 Added `Invalid authentication for Git Remote` to troubleshooting
  content/docs/command-reference/exp/list.md
  content/docs/command-reference/exp/pull.md
  content/docs/command-reference/exp/push.md
  content/docs/user-guide/troubleshooting.md
Labels: ⏳ awaiting-dvc-merge

#2842 fix: correct argument order
  content/docs/command-reference/remote/index.md
Labels: dvc-update
