Repository iterative/dvc.org, pull requests merged in 2021-04, with the labels that each got.

#2347 revisions to experiments in directories question
  content/blog/2021-03-31-march-21-community-gems.md
Labels: awaiting-response

#2334 exp show: Add info about wildcard patterns
  content/docs/command-reference/exp/show.md
Labels: ⏳ awaiting-dvc-merge

#2387 Remote modify: Added kerb_ticket option for HDFS
  content/docs/command-reference/remote/modify.md
Labels: ⏳ awaiting-dvc-merge

#2372 april heartbeat
  content/blog/2021-04-15-april-21-dvc-heartbeat.md
  static/uploads/images/2021-04-16/ai-singapore-logo.jpeg
  static/uploads/images/2021-04-16/april21cover.png
  static/uploads/images/2021-04-16/dagshub-dvc-love.png
  static/uploads/images/2021-04-16/longevity-study.png
  static/uploads/images/2021-04-16/made-with-ml-logo.png
  static/uploads/images/2021-04-16/open-science-labs-logo.png
Labels: ⏳ awaiting-dvc-merge

#2417 ref: corrections to `exp run/apply/branch` +
  content/docs/api-reference/make_checkpoint.md
  content/docs/command-reference/exp/apply.md
  content/docs/command-reference/exp/branch.md
  content/docs/command-reference/exp/run.md
  content/docs/user-guide/contributing/docs.md
Labels: 2.0 release
