Repository iterative/dvc.org, pull requests merged in 2021-06, with the labels that each got.

#2483 Updated S3 ssl_verify documentation
  content/docs/command-reference/remote/modify.md
Labels: dvc-update, ⏳ awaiting-dvc-merge

#2546 azure: remove note about bucket autocreation
  content/docs/command-reference/remote/modify.md
Labels: dvc-update

#2558 CML: replace cml-action => setup-cml
  content/blog/2021-02-22-cml-runner-prerelease.md
  content/blog/2021-03-03-dvc-2-0-release.md
  content/docs/cml/start-github.md
Labels: bug, doc-content, priority-p1

#2562 Document sharing folders with Google Drive service accounts
  content/docs/user-guide/setup-google-drive-remote.md
  static/img/gdrive-share-with-service-account.png
Labels: doc-content

#2489 azure: update docs for explicit anonymous login
  content/docs/command-reference/remote/add.md
  content/docs/command-reference/remote/modify.md
Labels: dvc-update
