Repository iterative/dvc.org, pull requests merged in 2021-12, with the labels that each got.

#3015 [WIP] cmd-ref: document exp init
  content/docs/command-reference/config.md
  content/docs/command-reference/exp/index.md
  content/docs/command-reference/exp/init.md
  content/docs/sidebar.json
Labels: p1-important

#2760 blog: collaborative experiments post
  content/blog/2021-12-13-collaborative-experiments.md
  static/uploads/images/2021-12-13/collaborative_exps.png
Labels: content/blog

#2782 cases: Data Science Experiment Tracking
  content/docs/sidebar.json
  content/docs/use-cases/experiment-tracking.md
  static/img/natural-experimentation.png
Labels: p1-important

#3097 Dec heartbeat
  content/blog/2021-12-15-december-21-heartbeat.md
  static/uploads/images/2021-12-15/Dario-Cazzani-2.png
  static/uploads/images/2021-12-15/arxiv.png
  static/uploads/images/2021-12-15/harshit-tyagi.jpeg
  static/uploads/images/2021-12-15/heartbeat-december.png
  static/uploads/images/2021-12-15/matt-segal.png
  static/uploads/images/2021-12-15/more-tools.png
  static/uploads/images/2021-12-15/natural-experimentation.png
  static/uploads/images/2021-12-15/office-hours-meetup.png
  static/uploads/images/2021-12-15/thoughtworks-mlops-landscape.png
Labels: content/blog

#3115 Update landing page
  src/components/Home/LandingHero/index.tsx
  src/components/Home/WhatsNewModal/index.tsx
Labels: team/web, website

#3117 Replace Google Analytics with Plausible
  gatsby-config.js
  gatsby-ssr.js
  package.json
  src/components/Community/Contribute/index.tsx
  src/components/Community/Events/index.tsx
  src/components/Community/Hero/index.tsx
  src/components/Community/Learn/index.tsx
  src/components/Community/Meet/index.tsx
  src/components/DownloadButton/index.tsx
  src/components/HamburgerMenu/index.tsx
  src/components/Home/LandingHero/index.tsx
  src/components/Home/LearnMore/index.tsx
  src/components/Home/UseCases/Video/index.tsx
  src/components/Home/index.tsx
  src/components/LayoutHeader/Nav/LinkItems/index.tsx
  src/components/LayoutHeader/Nav/Popup/index.tsx
  src/components/LayoutHeader/Nav/index.tsx
  src/components/Page/DefaultSEO/index.tsx
  src/components/SubscribeSection/Form/index.tsx
  src/utils/front/ga.ts
  src/utils/front/plausible.ts
  yarn.lock
Labels: team/web, website

#3107 Fix site crashing with certain anchor links
  src/components/Link/index.tsx
  src/components/Page/utils.ts
  src/utils/front/safeQuerySelector.ts
Labels: team/web

#3123 Fix bugs in analytics
  src/components/DownloadButton/index.tsx
  src/utils/front/plausible.ts
Labels: team/web, website

#3112 exp show: Add --keep and --drop
  content/docs/command-reference/exp/show.md
  content/docs/start/experiments.md
Labels: status/waiting-core-merge
