Repository iterative/dvc.org, pull requests merged in 2022-01, with the labels that each got.

#3152 Use `youtube-nocookie` domain in Video component
  src/components/Home/UseCases/Video/index.tsx
Labels: A: website

#3141 Add `prismjs` `dvctablehorizontals`
  config/prismjs/dvctable.js
  src/components/Documentation/Markdown/Main/styles.module.css
Labels: A: website

#3149 Fix broken tab order on docs sidebar menu
  src/components/Documentation/Layout/SidebarMenu/index.tsx
  src/components/Documentation/Layout/SidebarMenu/styles.module.css
Labels: 🐛 type: bug, A: website, website: eng-doc

#3157 Add `WhatsNewModal` Image Check
  src/components/Home/WhatsNewModal/index.tsx
Labels: 🐛 type: bug, A: website

#3169 live: remove 3rd party intro
  content/docs/dvclive/ml-frameworks/catalyst.md
  content/docs/dvclive/ml-frameworks/fastai.md
  content/docs/dvclive/ml-frameworks/huggingface.md
  content/docs/dvclive/ml-frameworks/keras.md
  content/docs/dvclive/ml-frameworks/lightgbm.md
  content/docs/dvclive/ml-frameworks/mmcv.md
  content/docs/dvclive/ml-frameworks/pytorch-lightning.md
  content/docs/dvclive/ml-frameworks/pytorch.md
  content/docs/dvclive/ml-frameworks/tensorflow.md
  content/docs/dvclive/ml-frameworks/xgboost.md
Labels: C: dvclive

#3140 Interactive synopsis Fix #2024
  config/prismjs/dvc-hook.js
  config/prismjs/usage.js
  gatsby-config.js
  plugins/gatsby-remark-args-linker/index.js
  plugins/gatsby-remark-args-linker/package.json
  plugins/gatsby-remark-dvc-linker/commandLinker.js
  src/components/Documentation/Markdown/Main/styles.module.css
  static/icons/index.js
  tsconfig.json
  yarn.lock
Labels: A: website, website: eng-doc, 👌 restyled

#3101 ref: Add `plots.auto_open` in `dvc.config`
  content/docs/command-reference/config.md
  content/docs/command-reference/exp/show.md
  content/docs/command-reference/plots/diff.md
  content/docs/command-reference/plots/show.md
Labels: C: ref

#3188 January heartbeat
  config/link-check/excluded-links.yml
  content/blog/2022-1-18-January-22-heartbeat.md
  static/uploads/images/2022-01-18/Conf42.png
  static/uploads/images/2022-01-18/abid-ali-awan.png
  static/uploads/images/2022-01-18/amit-kulkarni-studio.png
  static/uploads/images/2022-01-18/carl-handlin-rappibank.png
  static/uploads/images/2022-01-18/diego-jardim.png
  static/uploads/images/2022-01-18/forbes.jpeg
  static/uploads/images/2022-01-18/git-sql-cli.jpeg
  static/uploads/images/2022-01-18/heartbeat-january.png
  static/uploads/images/2022-01-18/hiring.jpeg
  static/uploads/images/2022-01-18/kdnuggets.jpeg
  static/uploads/images/2022-01-18/ryan-dawson-thoughtworks-cd4ml.png
  static/uploads/images/2022-01-18/stateful-training.png
Labels: C: blog

#3213 Remove broken `note` links
  content/docs/user-guide/project-structure/internal-files.md
Labels: C: guide

#3224 term: dataset (one word)
  content/docs/start/experiments.md
Labels: p2-nice-to-have, ❓ type: question

#3206 Stabilize Blog Post Meta Image Path
  gatsby-config.js
  gatsby-node.js
  package.json
  src/components/Blog/Post/HeroPic/index.tsx
  src/components/Blog/Post/index.tsx
  src/components/SEO/helper.ts
  src/components/SEO/index.tsx
  src/gatsby/models/blog/onCreateMarkdownContentNode.js
  src/templates/blog-post.tsx
  yarn.lock
Labels: type: enhancement, A: website

#3062 ref: review cache/etc. "corruption" concept...
  content/docs/command-reference/config.md
  content/docs/command-reference/remote/modify.md
  content/docs/command-reference/unprotect.md
  content/docs/user-guide/how-to/share-a-dvc-cache.md
  content/docs/user-guide/how-to/update-tracked-data.md
  content/docs/user-guide/large-dataset-optimization.md
Labels: p2-nice-to-have

#3199 ref: missing `adds --jobs`
  content/docs/command-reference/add.md
  content/docs/command-reference/remote/modify.md
Labels: 🐛 type: bug, C: ref

#3235 ref: misc. improvements around "stage" concept
  content/docs/command-reference/freeze.md
  content/docs/command-reference/import-url.md
  content/docs/command-reference/index.md
  content/docs/command-reference/plots/modify.md
  content/docs/user-guide/experiment-management/index.md
Labels: p2-nice-to-have

#3240 Stop list item markers from appearing in Google Chrome's auto dark mode
  src/components/LayoutHeader/Nav/styles.module.css
Labels: A: website
