Repository iterative/dvc.org, pull requests merged in 2024-02, with the labels that each got.

#5127 fix: video missing in docs
  src/server.js
Labels: p1-important

#5120 Add documentation for creating new projects via REST API
  content/docs/sidebar.json
  content/docs/studio/rest-api/create-project.md
  content/docs/studio/rest-api/download-model.md
  content/docs/studio/rest-api/index.md
Labels: A: docs, C: studio

#5108 Send live updates outside a git repo
  content/docs/studio/user-guide/experiments/live-metrics-and-plots.md
  content/docs/user-guide/integrations/databricks.md
  content/docs/user-guide/integrations/sagemaker.md
Labels: ⌛ status: wait-core-merge

#5131 change banner for feb 28
  src/components/Home/Alert/index.tsx
Labels: p1-important

#5145 fix: submit loading issue and add required fields sign
  src/components/Support/RequestAQuoteForm.tsx
Labels: p1-important

#5091 Add sso configuration docs
  content/docs/sidebar.json
  content/docs/studio/user-guide/single-sign-on.md
  content/docs/studio/user-guide/team-collaboration/index.md
Labels: ⌛ status: wait-core-merge
